from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from enum import StrEnum
from typing import Final

from sydel_doc_engine.domain.case_catalog import (
    CaseType,
    DocumentAvailability,
    ExpectedDocument,
    get_expected_documents,
)

DOC_006_SOURCE_V2_RESERVE: Final = (
    "La vraie V2 indique que ce document ne figure pas parmi les sources fournies ; "
    "generation moteur existante a afficher avec reserve dans le pilote SELARL."
)

SELARL_REQUIRED_CONDITIONS: Final[tuple[str, ...]] = (
    "profession",
    "site_distinct",
    "scm_cession",
    "regime_communautaire",
    "derogation",
    "cession",
    "cabinet_type",
)


class FieldRequirement(StrEnum):
    REQUIRED = "required"
    OPTIONAL = "optional"
    CONDITIONAL = "conditional"


class VariableCoverageStatus(StrEnum):
    UI_FIELD = "ui_field"
    REUSE_RULE = "reuse_rule"
    OUT_OF_SCOPE = "out_of_scope"
    TO_ARBITRATE = "to_arbitrate"


@dataclass(frozen=True)
class FormBlock:
    key: str
    label: str
    description: str


@dataclass(frozen=True)
class FormField:
    key: str
    label: str
    block_key: str
    variables: tuple[str, ...]
    requirement: FieldRequirement
    display_condition: str | None
    help_text: str
    example: str | None = None


@dataclass(frozen=True)
class ReuseRule:
    key: str
    label: str
    source: str
    target: str
    effect: str
    fields: tuple[str, ...]
    activation_condition: str


@dataclass(frozen=True)
class SelarlDocumentSpec:
    document_key: str
    document_label: str
    document_code: str | None
    block_key: str
    expected_availability: DocumentAvailability
    display_condition: str | None
    required_variables: tuple[str, ...]
    reserve_note: str | None = None


@dataclass(frozen=True)
class VariableCoverage:
    variable: str
    status: VariableCoverageStatus
    field_key: str | None = None
    reuse_rule_key: str | None = None
    note: str | None = None


SELARL_BLOCKS: Final[tuple[FormBlock, ...]] = (
    FormBlock("qualification", "Qualification du dossier", "Choix qui pilotent le flux SELARL."),
    FormBlock("societe", "Société", "Données de la SELARL en création."),
    FormBlock("siege_social", "Siège social", "Adresse juridique et domiciliation."),
    FormBlock(
        "professionnel_gerant",
        "Professionnel / gérant",
        "Identité du professionnel principal et du gérant.",
    ),
    FormBlock("ordre_professionnel", "Ordre professionnel", "Données ordinales et RPPS."),
    FormBlock("associes", "Associés", "Associés et répartition du capital."),
    FormBlock("mandataire_signataire", "Mandataire / signataire", "Signataire et mandataire."),
    FormBlock(
        "regime_conjoint",
        "Régime matrimonial / conjoint",
        "Conjoint et apport commun.",
    ),
    FormBlock("cession_cabinet", "Cession de cabinet", "Vendeur, acquéreur et cabinet cédé."),
    FormBlock("bail", "Bail", "Bailleur, locataire et locaux loués."),
    FormBlock("scm", "SCM", "Cession de parts de SCM vers la SELARL."),
    FormBlock("banque_financement", "Banque / financement", "Banque, prêt et crédit vendeur."),
    FormBlock("signature", "Signature", "Lieu, date et exemplaires de signature."),
)

SELARL_FIELDS: Final[tuple[FormField, ...]] = (
    FormField(
        "qualification.profession",
        "Profession exercée",
        "qualification",
        ("conditions.profession", "profession", "profession_reglementee"),
        FieldRequirement.REQUIRED,
        None,
        "Pilote les statuts SELARL et les mentions ordinales.",
        "médecin",
    ),
    FormField(
        "qualification.site_distinct",
        "Site distinct à déclarer",
        "qualification",
        ("conditions.site_distinct",),
        FieldRequirement.REQUIRED,
        None,
        "Affiche le formulaire site distinct comme pièce manuelle.",
        "non",
    ),
    FormField(
        "qualification.scm_cession",
        "Cession de parts de SCM vers la SELARL",
        "qualification",
        ("conditions.scm_cession",),
        FieldRequirement.REQUIRED,
        None,
        "Active les documents de cession SCM.",
        "oui",
    ),
    FormField(
        "qualification.regime_communautaire",
        "Régime matrimonial communautaire",
        "qualification",
        ("conditions.regime_communautaire",),
        FieldRequirement.REQUIRED,
        None,
        "Active les lettres conjoint et renonciation.",
        "oui",
    ),
    FormField(
        "qualification.derogation",
        "Dérogation ordinale",
        "qualification",
        ("conditions.derogation",),
        FieldRequirement.REQUIRED,
        None,
        "Affiche les documents de dérogation, tous manuels dans le pilote vérifié.",
        "non",
    ),
    FormField(
        "qualification.cession",
        "Cession de cabinet",
        "qualification",
        ("conditions.cession",),
        FieldRequirement.REQUIRED,
        None,
        "Active les blocs cession, bail et financement.",
        "oui",
    ),
    FormField(
        "qualification.cabinet_type",
        "Type de cabinet cédé",
        "qualification",
        ("conditions.cabinet_type",),
        FieldRequirement.CONDITIONAL,
        "cession = oui",
        "Choisir médical, dentaire ou aucun si la cession ne porte pas sur un cabinet.",
        "cabinet dentaire",
    ),
    FormField(
        "societe.denomination",
        "Dénomination de la SELARL",
        "societe",
        ("denomination_societe",),
        FieldRequirement.REQUIRED,
        None,
        "Nom de la société utilisée dans les documents SELARL.",
        "SELARL DU CENTRE",
    ),
    FormField(
        "societe.forme_sociale",
        "Forme sociale de la SELARL",
        "societe",
        ("forme_sociale", "forme_sociale_complete"),
        FieldRequirement.REQUIRED,
        None,
        "Valeur pilote : SELARL, avec libellé complet pour les statuts.",
        "SELARL",
    ),
    FormField(
        "societe.capital_social",
        "Capital social de la SELARL",
        "societe",
        ("capital_social", "capital_lettres"),
        FieldRequirement.REQUIRED,
        None,
        "Montant du capital en chiffres et en lettres si le document le demande.",
        "5 000 euros",
    ),
    FormField(
        "societe.parts",
        "Capital de la SELARL - parts sociales",
        "societe",
        ("nb_parts", "nb_parts_total", "valeur_nominale_part"),
        FieldRequirement.CONDITIONAL,
        "PV nomination gérant ou statuts actifs",
        "Nombre total de parts et valeur nominale.",
        "500 parts de 10 euros",
    ),
    FormField(
        "societe.rcs",
        "Immatriculation de la SELARL",
        "societe",
        ("ville_rcs", "numero_rcs"),
        FieldRequirement.CONDITIONAL,
        "documents de statuts, bail ou SCM actifs",
        "Ville et numéro RCS lorsque la source les demande.",
        "RCS Paris",
    ),
    FormField(
        "siege_social.numero",
        "Adresse du siège social - numéro",
        "siege_social",
        ("num_voie_siege",),
        FieldRequirement.REQUIRED,
        None,
        "Numéro de voie du siège, distinct des autres adresses du dossier.",
        "12",
    ),
    FormField(
        "siege_social.voie",
        "Adresse du siège social - voie",
        "siege_social",
        ("voie_siege",),
        FieldRequirement.REQUIRED,
        None,
        "Voie du siège social de la SELARL.",
        "rue de la Paix",
    ),
    FormField(
        "siege_social.cp",
        "Adresse du siège social - code postal",
        "siege_social",
        ("cp_siege",),
        FieldRequirement.REQUIRED,
        None,
        "Code postal du siège social.",
        "75002",
    ),
    FormField(
        "siege_social.ville",
        "Adresse du siège social - ville",
        "siege_social",
        ("ville_siege", "adresse_siege"),
        FieldRequirement.REQUIRED,
        None,
        "Ville du siège social.",
        "Paris",
    ),
    FormField(
        "siege_social.domiciliation",
        "Adresse de domiciliation affichée",
        "siege_social",
        ("domiciliation.adresse_affichee",),
        FieldRequirement.CONDITIONAL,
        "DOC-002 actif",
        "Adresse affichée dans l'autorisation de domiciliation.",
        "12 rue de la Paix, 75002 Paris",
    ),
    FormField(
        "professionnel.identite",
        "Identité du professionnel principal",
        "professionnel_gerant",
        ("civilite", "prenom", "nom"),
        FieldRequirement.REQUIRED,
        None,
        "Personne pivot du dossier, réutilisable comme gérant ou signataire.",
        "Dr Camille Martin",
    ),
    FormField(
        "professionnel.naissance",
        "Naissance du professionnel principal",
        "professionnel_gerant",
        ("date_naissance", "ville_naissance", "departement_naissance"),
        FieldRequirement.REQUIRED,
        None,
        "Date et lieu de naissance du professionnel principal.",
        "03/04/1985 à Lyon",
    ),
    FormField(
        "professionnel.filiation_nationalite",
        "Nationalité et filiation du professionnel principal",
        "professionnel_gerant",
        ("nationalite", "nom_pere", "nom_mere"),
        FieldRequirement.CONDITIONAL,
        "documents communs ou statuts actifs",
        "Données demandées par la non-condamnation et certains statuts.",
        "française",
    ),
    FormField(
        "professionnel.adresse_personnelle",
        "Adresse personnelle du professionnel",
        "professionnel_gerant",
        (
            "num_voie_perso",
            "voie_perso",
            "cp_perso",
            "ville_perso",
            "adresse_personnelle",
        ),
        FieldRequirement.REQUIRED,
        None,
        "Adresse personnelle, distincte du siège, du cabinet et de la banque.",
        "8 avenue Victor Hugo, 69002 Lyon",
    ),
    FormField(
        "professionnel.fonction",
        "Fonction du professionnel principal",
        "professionnel_gerant",
        ("fonction_dirigeant", "profession_personne_1"),
        FieldRequirement.REQUIRED,
        None,
        "Pour la SELARL pilote, utiliser Gérant / professionnel principal.",
        "Gérant",
    ),
    FormField(
        "ordre.numeros",
        "Identifiants ordinaux du professionnel",
        "ordre_professionnel",
        ("ordre_departemental", "numero_ordre", "numero_rpps"),
        FieldRequirement.CONDITIONAL,
        "demande d'inscription, statuts ou cession actifs",
        "Numéro d'ordre, RPPS et conseil départemental.",
        "75-12345",
    ),
    FormField(
        "ordre.adresse_conseil",
        "Adresse du conseil de l'ordre",
        "ordre_professionnel",
        ("adresse_conseil_ordre", "cp_ordre", "ville_ordre"),
        FieldRequirement.CONDITIONAL,
        "DOC-034 actif",
        "Adresse du conseil, distincte du siège et de l'adresse personnelle.",
        "10 rue du Conseil, 75000 Paris",
    ),
    FormField(
        "ordre.adresse_lieu_exercice",
        "Adresse du lieu d'exercice",
        "ordre_professionnel",
        ("adresse_lieu_exercice",),
        FieldRequirement.CONDITIONAL,
        "statuts chirurgien-dentiste actifs",
        "Adresse professionnelle d'exercice demandée par la V2.",
        "4 rue du Cabinet, 75015 Paris",
    ),
    FormField(
        "associes.nombre",
        "Nombre d'associés de la SELARL",
        "associes",
        ("associes.cardinalite",),
        FieldRequirement.REQUIRED,
        "PV nomination gérant ou statuts actifs",
        "Permet de borner les cas simples V1.",
        "1",
    ),
    FormField(
        "associes.associe_1",
        "Associé 1 - identité et parts",
        "associes",
        (
            "civilite_personne_1",
            "prenom_personne_1",
            "nom_personne_1",
            "adresse_perso_personne_1",
            "nationalite_personne_1",
            "parts_personne_1",
        ),
        FieldRequirement.REQUIRED,
        "PV nomination gérant ou statuts actifs",
        "Peut être alimenté depuis le professionnel principal ou le signataire.",
        "Dr Camille Martin, 500 parts",
    ),
    FormField(
        "associes.associe_2",
        "Associé 2 - identité et parts",
        "associes",
        (
            "civilite_personne_2",
            "prenom_personne_2",
            "nom_personne_2",
            "adresse_perso_personne_2",
            "nationalite_personne_2",
            "parts_personne_2",
            "nb_parts_personne_2",
        ),
        FieldRequirement.CONDITIONAL,
        "nombre d'associés >= 2",
        "À afficher seulement dans les cas simples couverts en V1.",
        "Dr Alex Bernard, 100 parts",
    ),
    FormField(
        "mandataire.identite",
        "Identité du mandataire",
        "mandataire_signataire",
        (
            "civilite_mandataire",
            "prenom_mandataire",
            "nom_mandataire",
            "fonction_mandataire",
            "denomination_cabinet_mandataire",
        ),
        FieldRequirement.CONDITIONAL,
        "mandataire distinct du signataire",
        "Personne ou cabinet qui dépose ou signe la demande.",
        "Me Dupont",
    ),
    FormField(
        "mandataire.signataire",
        "Identité du signataire",
        "mandataire_signataire",
        ("prenom_signataire", "nom_signataire"),
        FieldRequirement.CONDITIONAL,
        "signataire distinct du professionnel principal",
        "Signataire affiché dans les documents qui l'exigent.",
        "Camille Martin",
    ),
    FormField(
        "regime.conjoint",
        "Identité du conjoint",
        "regime_conjoint",
        ("prenom_conjoint", "nom_conjoint"),
        FieldRequirement.CONDITIONAL,
        "régime communautaire = oui",
        "Conjoint concerné par les lettres de renonciation ou avertissement.",
        "Sophie Martin",
    ),
    FormField(
        "regime.apport",
        "Apport soumis au régime communautaire",
        "regime_conjoint",
        ("apport_personne_1", "apport_lettres_personne_1"),
        FieldRequirement.CONDITIONAL,
        "régime communautaire = oui",
        "Montant ou apport concerné par la renonciation.",
        "5 000 euros",
    ),
    FormField(
        "cession.vendeur",
        "Vendeur du cabinet",
        "cession_cabinet",
        (
            "civilite_vendeur",
            "prenom_vendeur",
            "nom_vendeur",
            "profession_vendeur",
            "date_naissance_vendeur",
            "nationalite_vendeur",
        ),
        FieldRequirement.CONDITIONAL,
        "cession = oui",
        "Personne ou société qui cède le cabinet.",
        "Dr Jean Durand",
    ),
    FormField(
        "cession.adresse_vendeur",
        "Adresse du vendeur",
        "cession_cabinet",
        ("adresse_vendeur",),
        FieldRequirement.CONDITIONAL,
        "cession = oui",
        "Adresse du vendeur, distincte du cabinet et du siège acquéreur.",
        "8 avenue du Vendeur, 69002 Lyon",
    ),
    FormField(
        "cession.adresse_exercice_vendeur",
        "Adresse d'exercice du vendeur",
        "cession_cabinet",
        ("adresse_exercice_vendeur",),
        FieldRequirement.CONDITIONAL,
        "acte de cession cabinet médical actif",
        "Adresse professionnelle d'exercice du vendeur.",
        "4 rue du Cabinet, 75015 Paris",
    ),
    FormField(
        "cession.adresse_cabinet",
        "Adresse du cabinet cédé",
        "cession_cabinet",
        ("adresse_cabinet", "telephone_cabinet"),
        FieldRequirement.CONDITIONAL,
        "cession = oui",
        "Adresse du cabinet vendu.",
        "4 rue du Cabinet, 75015 Paris",
    ),
    FormField(
        "cession.adresse_locaux",
        "Adresse des locaux loués",
        "cession_cabinet",
        ("adresse_locaux",),
        FieldRequirement.CONDITIONAL,
        "compromis médical ou dentaire actif",
        "Adresse des locaux, distincte de l'adresse personnelle du vendeur.",
        "4 rue des Locaux, 75015 Paris",
    ),
    FormField(
        "cession.acquereur",
        "Acquéreur du cabinet",
        "cession_cabinet",
        (
            "denomination_societe_acquereur",
            "forme_sociale_acquereur",
            "capital_social_acquereur",
            "adresse_siege_acquereur",
            "ville_rcs_acquereur",
        ),
        FieldRequirement.CONDITIONAL,
        "cession = oui",
        "Peut être dérivé de la SELARL en création.",
        "SELARL DU CENTRE",
    ),
    FormField(
        "cession.prix",
        "Prix de cession du cabinet",
        "cession_cabinet",
        (
            "prix_cession",
            "prix_cession_lettres",
            "prix_elements_corporels",
            "prix_elements_incorporels",
        ),
        FieldRequirement.CONDITIONAL,
        "cession = oui",
        "Prix global et ventilation corporels/incorporels si demandée.",
        "120 000 euros",
    ),
    FormField(
        "cession.activite",
        "Historique et activité du cabinet",
        "cession_cabinet",
        (
            "date_origine_propriete",
            "annees_acquisition_patientele",
            "description_origine_propriete",
            "exercice_1",
            "chiffre_affaires_1",
            "resultat_1",
        ),
        FieldRequirement.CONDITIONAL,
        "cession = oui",
        "Historique et données économiques demandés par les actes.",
        "CA 2025 : 250 000 euros",
    ),
    FormField(
        "cession.salaries",
        "Salariés repris avec le cabinet dentaire",
        "cession_cabinet",
        (
            "civilite_salarie_1",
            "prenom_salarie_1",
            "nom_salarie_1",
            "civilite_salarie_2",
            "prenom_salarie_2",
            "nom_salarie_2",
        ),
        FieldRequirement.CONDITIONAL,
        "acte de cession cabinet dentaire actif",
        "Liste bornée aux salariés prévus par la source V2.",
        "Mme Alice Bernard",
    ),
    FormField(
        "bail.bailleur",
        "Bailleur des locaux",
        "bail",
        (
            "civilite_bailleur",
            "prenom_bailleur",
            "nom_bailleur",
            "profession_bailleur",
        ),
        FieldRequirement.CONDITIONAL,
        "cession = oui et bail actif",
        "Identité du bailleur des locaux.",
        "SCI DES LOCAUX",
    ),
    FormField(
        "bail.adresse_bailleur",
        "Adresse du bailleur",
        "bail",
        ("adresse_bailleur",),
        FieldRequirement.CONDITIONAL,
        "bail actif",
        "Adresse du bailleur, distincte des locaux loués.",
        "2 rue du Bailleur, 75008 Paris",
    ),
    FormField(
        "bail.locataire",
        "Locataire du bail",
        "bail",
        (
            "civilite_locataire",
            "prenom_locataire",
            "nom_locataire",
            "profession_locataire",
        ),
        FieldRequirement.CONDITIONAL,
        "avenant bail actif",
        "Locataire au bail, distinct du vendeur si le dossier le prévoit.",
        "Dr Jean Durand",
    ),
    FormField(
        "bail.adresse_locataire",
        "Adresse du locataire",
        "bail",
        ("adresse_locataire",),
        FieldRequirement.CONDITIONAL,
        "avenant bail actif",
        "Adresse du locataire, pas celle du bailleur ni celle des locaux.",
        "8 rue du Locataire, 75014 Paris",
    ),
    FormField(
        "bail.conditions",
        "Dates et conditions du bail",
        "bail",
        (
            "date_bail",
            "duree_bail",
            "date_debut_bail",
            "date_fin_bail",
            "superficie_local",
            "loyer_mensuel",
        ),
        FieldRequirement.CONDITIONAL,
        "bail actif",
        "Dates, superficie et loyer du bail repris dans les documents.",
        "Bail du 01/01/2025",
    ),
    FormField(
        "scm.cedant",
        "Cédant des parts SCM",
        "scm",
        (
            "civilite_cedant",
            "prenom_cedant",
            "nom_cedant",
            "profession_cedant",
            "date_naissance_cedant",
            "nationalite_cedant",
        ),
        FieldRequirement.CONDITIONAL,
        "SCM cession = oui",
        "Personne qui cède les parts de SCM.",
        "Dr Jean Durand",
    ),
    FormField(
        "scm.adresse_cedant",
        "Adresse du cédant SCM",
        "scm",
        ("adresse_cedant",),
        FieldRequirement.CONDITIONAL,
        "SCM cession = oui",
        "Adresse du cédant des parts de SCM.",
        "6 rue du Cédant, 75011 Paris",
    ),
    FormField(
        "scm.cessionnaire",
        "Cessionnaire des parts SCM",
        "scm",
        (
            "denomination_societe_cessionnaire",
            "capital_social_cessionnaire",
            "adresse_siege_cessionnaire",
            "ville_rcs_cessionnaire",
        ),
        FieldRequirement.CONDITIONAL,
        "SCM cession = oui",
        "Peut être dérivé de la SELARL en création.",
        "SELARL DU CENTRE",
    ),
    FormField(
        "scm.adresse_cessionnaire",
        "Adresse du cessionnaire SCM",
        "scm",
        ("adresse_siege_cessionnaire",),
        FieldRequirement.CONDITIONAL,
        "SCM cession = oui",
        "Adresse du cessionnaire des parts SCM, dérivable du siège SELARL.",
        "12 rue du Siège, 75002 Paris",
    ),
    FormField(
        "scm.scm_cedee",
        "SCM cédée",
        "scm",
        (
            "denomination_societe_cedee",
            "capital_social_societe_cedee",
            "nb_parts_total_societe_cedee",
            "ville_rcs_societe_cedee",
            "numero_rcs_societe_cedee",
        ),
        FieldRequirement.CONDITIONAL,
        "SCM cession = oui",
        "Société civile de moyens dont les parts sont cédées.",
        "SCM DES DOCTEURS",
    ),
    FormField(
        "scm.adresse_scm_cedee",
        "Adresse de la SCM cédée",
        "scm",
        ("scm_cession.scm_cedee.adresse_a_arbitrer",),
        FieldRequirement.CONDITIONAL,
        "SCM cession = oui si adresse distincte à arbitrer",
        "Adresse à confirmer si elle ne se déduit pas du siège cessionnaire.",
        "12 rue du Siège, 75002 Paris",
    ),
    FormField(
        "scm.prix",
        "Prix de cession des parts SCM",
        "scm",
        (
            "nb_parts_cedees",
            "prix_unitaire_part",
            "prix_unitaire_part_lettres",
            "prix_global_parts",
            "prix_global_parts_lettres",
        ),
        FieldRequirement.CONDITIONAL,
        "SCM cession = oui",
        "Prix des parts SCM, distinct du prix du cabinet.",
        "1 000 euros",
    ),
    FormField(
        "scm.enregistrement",
        "Adresse du service d'enregistrement SCM",
        "scm",
        ("montant_droits_enregistrement",),
        FieldRequirement.CONDITIONAL,
        "courrier SDE cession SCM actif",
        "Adresse ou service SDE à arbitrer si demandé par le futur écran.",
        "SDE Paris",
    ),
    FormField(
        "banque.banque",
        "Banque de financement",
        "banque_financement",
        ("nom_banque",),
        FieldRequirement.CONDITIONAL,
        "financement bancaire actif",
        "Banque concernée par l'appel de fonds ou les statuts.",
        "Banque X",
    ),
    FormField(
        "banque.adresse_banque",
        "Adresse de la banque",
        "banque_financement",
        ("adresse_banque",),
        FieldRequirement.CONDITIONAL,
        "banque active",
        "Adresse de la banque, pas celle du siège social.",
        "1 boulevard Haussmann, 75009 Paris",
    ),
    FormField(
        "banque.pret",
        "Prêt de cession",
        "banque_financement",
        ("montant_pret", "taux_pret", "duree_pret"),
        FieldRequirement.CONDITIONAL,
        "compromis avec condition de prêt actif",
        "Prêt de cession, distinct de l'emprunt du PV nomination gérant.",
        "100 000 euros sur 84 mois",
    ),
    FormField(
        "banque.credit_vendeur",
        "Crédit vendeur",
        "banque_financement",
        (
            "montant_credit_vendeur",
            "duree_credit_vendeur",
            "taux_credit_vendeur",
            "majoration_interet_retard",
        ),
        FieldRequirement.CONDITIONAL,
        "acte ou cession SCM avec crédit vendeur",
        "Modalités du crédit vendeur.",
        "20 000 euros sur 24 mois",
    ),
    FormField(
        "banque.emprunt_pv",
        "Emprunt autorisé dans le PV nomination gérant",
        "banque_financement",
        ("emprunt.montant_max",),
        FieldRequirement.CONDITIONAL,
        "emprunt PV actif",
        "Option du DOC-004, pas un document autonome.",
        "250 000 euros",
    ),
    FormField(
        "banque.adresse_bien_finance",
        "Adresse du bien financé par l'emprunt",
        "banque_financement",
        ("bien_immobilier.adresse",),
        FieldRequirement.CONDITIONAL,
        "emprunt PV actif",
        "Adresse du bien immobilier visé par l'emprunt.",
        "10 rue du Bien, 75010 Paris",
    ),
    FormField(
        "signature.lieu_date",
        "Lieu et date de signature",
        "signature",
        ("lieu_signature", "date_signature", "date_du_jour"),
        FieldRequirement.REQUIRED,
        "au moins un document signé actif",
        "Lieu et date affichés dans les documents.",
        "Paris, 19/05/2026",
    ),
    FormField(
        "signature.exemplaires",
        "Nombre d'exemplaires et de pages",
        "signature",
        ("nombre_exemplaires_lettres", "nombre_pages_lettres"),
        FieldRequirement.CONDITIONAL,
        "document source demandant les exemplaires",
        "À masquer si aucun document actif ne le consomme.",
        "trois exemplaires",
    ),
    FormField(
        "signature.signatures_cession",
        "Signatures acquéreur et vendeur",
        "signature",
        ("signature_acquereur", "signature_vendeur"),
        FieldRequirement.CONDITIONAL,
        "cession de cabinet actif",
        "Zones de signature des actes ou compromis.",
        "Signature acquéreur",
    ),
)

SELARL_REUSE_RULES: Final[tuple[ReuseRule, ...]] = (
    ReuseRule(
        "signataire_is_associe_1",
        "Le signataire est le premier associé",
        "mandataire_signataire.signataire",
        "associes.associe_1",
        "Copie l'identité du signataire vers l'associé 1 et verrouille les champs dérivés.",
        (
            "civilite_personne_1",
            "prenom_personne_1",
            "nom_personne_1",
            "profession_personne_1",
            "adresse_perso_personne_1",
            "nationalite_personne_1",
        ),
        "au moins un associé et case cochée",
    ),
    ReuseRule(
        "gerant_is_professional",
        "Le gérant est le professionnel principal",
        "professionnel_gerant",
        "dirigeant_nomine",
        "Alimente le gérant depuis le professionnel principal et évite la double saisie.",
        (
            "civilite_personne_1",
            "prenom_personne_1",
            "nom_personne_1",
            "date_naissance_personne_1",
            "ville_naissance_personne_1",
            "adresse_perso_personne_1",
        ),
        "PV nomination gérant ou statuts actifs",
    ),
    ReuseRule(
        "signataire_is_professional",
        "Le signataire est le professionnel principal",
        "professionnel_gerant",
        "mandataire_signataire.signataire",
        "Alimente le signataire depuis le professionnel principal.",
        ("prenom_signataire", "nom_signataire", "civilite"),
        "case cochée ou valeur par défaut SELARL simple",
    ),
    ReuseRule(
        "mandataire_is_signataire",
        "Le mandataire est le signataire",
        "mandataire_signataire.signataire",
        "mandataire_signataire.mandataire",
        "Copie l'identité du signataire vers le mandataire.",
        ("civilite_mandataire", "prenom_mandataire", "nom_mandataire"),
        "DOC-034 actif et mandataire non distinct",
    ),
    ReuseRule(
        "selarl_is_acquirer",
        "La SELARL en création est l'acquéreur",
        "societe",
        "cession_cabinet.acquereur",
        "Alimente l'acquéreur du cabinet depuis la SELARL.",
        (
            "denomination_societe_acquereur",
            "forme_sociale_acquereur",
            "capital_social_acquereur",
            "adresse_siege_acquereur",
            "ville_rcs_acquereur",
            "numero_rcs_acquereur",
        ),
        "cession = oui et case cochée",
    ),
    ReuseRule(
        "selarl_is_scm_transferee",
        "La SELARL en création est la cessionnaire des parts SCM",
        "societe",
        "scm.cessionnaire",
        "Alimente le cessionnaire SCM depuis la SELARL.",
        (
            "denomination_societe_cessionnaire",
            "capital_social_cessionnaire",
            "adresse_siege_cessionnaire",
            "ville_rcs_cessionnaire",
        ),
        "SCM cession = oui et case cochée",
    ),
    ReuseRule(
        "domiciliation_is_registered_office",
        "L'adresse de domiciliation est le siège social",
        "siege_social",
        "siege_social.domiciliation",
        "Construit l'adresse de domiciliation affichée depuis le siège social.",
        ("domiciliation.adresse_affichee",),
        "DOC-002 actif et case cochée",
    ),
)

SELARL_DOCUMENTS: Final[tuple[SelarlDocumentSpec, ...]] = (
    SelarlDocumentSpec(
        "declaration_non_condamnation",
        "Déclaration sur l'honneur de non-condamnation",
        "DOC-001",
        "professionnel_gerant",
        DocumentAvailability.GENERATABLE,
        None,
        ("civilite", "prenom", "nom", "date_naissance", "num_voie_perso"),
    ),
    SelarlDocumentSpec(
        "autorisation_domiciliation",
        "Autorisation de domiciliation",
        "DOC-002",
        "siege_social",
        DocumentAvailability.GENERATABLE,
        None,
        ("denomination_societe", "capital_social", "num_voie_siege", "voie_siege"),
    ),
    SelarlDocumentSpec(
        "procuration",
        "Procuration",
        "DOC-003",
        "mandataire_signataire",
        DocumentAvailability.GENERATABLE,
        None,
        ("civilite", "prenom", "nom", "fonction_dirigeant", "denomination_societe"),
    ),
    SelarlDocumentSpec(
        "pv_nomination_gerant",
        "PV nomination gérant",
        "DOC-004",
        "associes",
        DocumentAvailability.GENERATABLE,
        None,
        ("denomination_societe", "capital_social", "nb_parts", "civilite_personne_1"),
    ),
    SelarlDocumentSpec(
        "demande_inscription_ordre",
        "Demande d'inscription à l'ordre",
        "DOC-034",
        "ordre_professionnel",
        DocumentAvailability.GENERATABLE,
        None,
        ("profession_reglementee", "adresse_conseil_ordre", "cp_ordre", "ville_ordre"),
    ),
    SelarlDocumentSpec(
        "statuts_selarl_chirurgien_dentiste",
        "Statuts SELARL chirurgien-dentiste",
        "DOC-016",
        "societe",
        DocumentAvailability.GENERATABLE,
        "profession = chirurgien_dentiste",
        ("forme_sociale_complete", "adresse_lieu_exercice", "numero_rpps"),
    ),
    SelarlDocumentSpec(
        "statuts_selarl_medecin",
        "Statuts SELARL médecin",
        "DOC-017",
        "societe",
        DocumentAvailability.GENERATABLE,
        "profession = medecin",
        ("adresse_banque", "numero_ordre", "numero_rpps"),
    ),
    SelarlDocumentSpec(
        "site_distinct_cd94_sel",
        "Formulaire de déclaration préalable de site distinct CD94 avec la SEL",
        None,
        "ordre_professionnel",
        DocumentAvailability.MANUAL_ONLY,
        "site_distinct = oui",
        (),
        "La V2 indique un document à remplir à la main.",
    ),
    SelarlDocumentSpec(
        "pv_age_cession_parts_scm",
        "PV AGE cession part SCM",
        "DOC-031",
        "scm",
        DocumentAvailability.GENERATABLE,
        "scm_cession = oui",
        ("denomination_societe", "nb_parts_total", "parts_personne_1"),
    ),
    SelarlDocumentSpec(
        "courrier_sde_cession_scm",
        "Courrier SDE cession SCM",
        "DOC-032",
        "scm",
        DocumentAvailability.GENERATABLE,
        "scm_cession = oui",
        ("montant_droits_enregistrement", "prenom_signataire", "nom_signataire"),
    ),
    SelarlDocumentSpec(
        "acte_cession_parts_scm_sel",
        "Acte de cession des parts de la SCM vers SELARL",
        "DOC-033",
        "scm",
        DocumentAvailability.GENERATABLE,
        "scm_cession = oui",
        ("adresse_cedant", "adresse_siege_cessionnaire", "prix_global_parts"),
    ),
    SelarlDocumentSpec(
        "lettre_renonciation_associe",
        "Lettre de renonciation à revendiquer la qualité d'associé",
        "DOC-005",
        "regime_conjoint",
        DocumentAvailability.GENERATABLE,
        "regime_communautaire = oui",
        ("apport_personne_1", "apport_lettres_personne_1", "prenom_conjoint"),
    ),
    SelarlDocumentSpec(
        "lettre_avertissement_conjoint",
        "Lettre d'avertissement au conjoint",
        "DOC-006",
        "regime_conjoint",
        DocumentAvailability.GENERATABLE,
        "regime_communautaire = oui",
        (),
        DOC_006_SOURCE_V2_RESERVE,
    ),
    SelarlDocumentSpec(
        "formulaire_derogation_sites_sel",
        "Formulaire de dérogation pour exercer sur plusieurs sites avec la SEL",
        "DOC-013",
        "ordre_professionnel",
        DocumentAvailability.MANUAL_ONLY,
        "derogation = oui",
        (),
        "Formulaire non fourni dans les sources variables V2 ; hors génération pilote.",
    ),
    SelarlDocumentSpec(
        "derogation_sel_bnc",
        "Dérogation SEL BNC",
        None,
        "qualification",
        DocumentAvailability.MANUAL_ONLY,
        "derogation = oui",
        (),
        "La V2 indique un document à remplir à la main.",
    ),
    SelarlDocumentSpec(
        "derogation_cumul_selarl_bnc",
        "Dérogation cumul SELARL BNC",
        "DOC-014",
        "qualification",
        DocumentAvailability.MANUAL_ONLY,
        "derogation = oui",
        (),
        "La V2 indique explicitement un document à remplir à la main.",
    ),
    SelarlDocumentSpec(
        "avenant_contrat_bail",
        "Avenant contrat de bail",
        "DOC-007",
        "bail",
        DocumentAvailability.GENERATABLE,
        "cession = oui",
        ("adresse_bailleur", "adresse_locataire", "date_bail"),
    ),
    SelarlDocumentSpec(
        "appel_fonds_sel",
        "Appel de fonds SEL",
        "DOC-008",
        "banque_financement",
        DocumentAvailability.GENERATABLE,
        "cession = oui",
        ("nom_banque", "denomination_societe_acquereur", "prenom_signataire"),
    ),
    SelarlDocumentSpec(
        "acte_cession_cabinet_medical",
        "Acte de cession d'un cabinet médical",
        "DOC-009",
        "cession_cabinet",
        DocumentAvailability.GENERATABLE,
        "cession = oui et cabinet_type = medical",
        ("adresse_vendeur", "adresse_exercice_vendeur", "adresse_cabinet"),
    ),
    SelarlDocumentSpec(
        "compromis_cession_cabinet_medical",
        "Compromis de cession d'un cabinet médical",
        "DOC-010",
        "cession_cabinet",
        DocumentAvailability.GENERATABLE,
        "cession = oui et cabinet_type = medical",
        ("adresse_vendeur", "adresse_cabinet", "adresse_locaux", "montant_pret"),
    ),
    SelarlDocumentSpec(
        "acte_cession_cabinet_dentaire",
        "Acte de cession d'un cabinet dentaire",
        "DOC-011",
        "cession_cabinet",
        DocumentAvailability.GENERATABLE,
        "cession = oui et cabinet_type = dentaire",
        ("adresse_vendeur", "telephone_cabinet", "civilite_salarie_1"),
    ),
    SelarlDocumentSpec(
        "compromis_cession_cabinet_dentaire",
        "Compromis de cession d'un cabinet dentaire",
        "DOC-012",
        "cession_cabinet",
        DocumentAvailability.GENERATABLE,
        "cession = oui et cabinet_type = dentaire",
        ("adresse_vendeur", "adresse_cabinet", "adresse_locaux", "montant_pret"),
    ),
)

SELARL_V2_VARIABLES_BY_DOCUMENT: Final[dict[str, tuple[str, ...]]] = {
    "DOC-001": (
        "civilite",
        "prenom",
        "nom",
        "date_naissance",
        "num_voie_perso",
        "voie_perso",
        "cp_perso",
        "ville_perso",
        "nationalite",
        "nom_pere",
        "nom_mere",
        "lieu_signature",
        "date_signature",
    ),
    "DOC-002": (
        "civilite",
        "prenom",
        "nom",
        "denomination_societe",
        "capital_social",
        "num_voie_siege",
        "voie_siege",
        "cp_siege",
        "ville_siege",
        "lieu_signature",
        "date_signature",
    ),
    "DOC-003": (
        "civilite",
        "prenom",
        "nom",
        "num_voie_perso",
        "voie_perso",
        "cp_perso",
        "ville_perso",
        "fonction_dirigeant",
        "denomination_societe",
        "num_voie_siege",
        "voie_siege",
        "cp_siege",
        "ville_siege",
        "lieu_signature",
        "date_signature",
    ),
    "DOC-004": (
        "denomination_societe",
        "forme_sociale",
        "capital_social",
        "num_voie_siege",
        "voie_siege",
        "cp_siege",
        "ville_siege",
        "date_decision",
        "date_reunion_lettres",
        "nb_parts",
        "valeur_nominale_part",
        "denomination_societe_1",
        "nb_parts_societe_1",
        "prenom_personne_2",
        "nom_personne_2",
        "nb_parts_personne_2",
        "civilite_personne_1",
        "prenom_personne_1",
        "nom_personne_1",
        "profession_personne_1",
        "date_naissance_personne_1",
        "ville_naissance_personne_1",
        "adresse_perso_personne_1",
        "nationalite_personne_1",
        "civilite_personne_2",
        "profession_personne_2",
        "date_naissance_personne_2",
        "ville_naissance_personne_2",
        "adresse_perso_personne_2",
        "nationalite_personne_2",
        "lieu_signature",
    ),
    "DOC-034": (
        "prenom",
        "nom",
        "profession_reglementee",
        "adresse_personnelle",
        "profession_reglementee_pluriel",
        "adresse_conseil_ordre",
        "cp_ordre",
        "ville_ordre",
        "lieu_signature",
        "date_signature",
        "denomination_societe",
        "civilite_mandataire",
        "prenom_mandataire",
        "nom_mandataire",
        "fonction_mandataire",
        "denomination_cabinet_mandataire",
    ),
    "DOC-016": (
        "denomination_societe",
        "forme_sociale_complete",
        "profession_reglementee",
        "capital_social",
        "adresse_siege",
        "civilite",
        "prenom",
        "nom",
        "profession",
        "date_naissance",
        "ville_naissance",
        "departement_naissance",
        "nationalite",
        "adresse_personnelle",
        "profession_reglementee_pluriel",
        "ordre_departemental",
        "numero_rpps",
        "forme_sociale",
        "adresse_lieu_exercice",
        "duree_societe",
        "montant_apport",
        "montant_apport_lettres",
        "nom_banque",
        "capital_lettres",
        "nb_parts_total",
        "valeur_nominale_part",
        "debut_exercice",
        "fin_exercice",
        "date_cloture_exercice_1",
        "prestataire_signature_electronique",
        "lieu_signature",
        "date_signature",
    ),
    "DOC-017": (
        "denomination_societe",
        "capital_social",
        "adresse_siege",
        "civilite",
        "prenom",
        "nom",
        "profession",
        "date_naissance",
        "ville_naissance",
        "departement_naissance",
        "nationalite",
        "adresse_personnelle",
        "ville_ordre",
        "numero_ordre",
        "numero_rpps",
        "forme_sociale_complete",
        "capital_lettres",
        "nom_banque",
        "adresse_banque",
        "nb_parts_total",
        "valeur_nominale_part",
        "civilite_personne_2",
        "prenom_personne_2",
        "nom_personne_2",
        "seuil_achat_materiel",
        "seuil_emprunt_gerance",
        "date_cloture_exercice_1",
        "lieu_signature",
        "date_signature",
        "nombre_exemplaires_lettres",
        "prenom_signataire",
        "nom_signataire",
    ),
    "DOC-031": (
        "denomination_societe",
        "capital_social",
        "adresse_siege",
        "ville_rcs",
        "numero_rcs",
        "date_du_jour",
        "date_pv_lettres",
        "nb_parts_total",
        "valeur_nominale_part",
        "civilite_personne_1",
        "prenom_personne_1",
        "nom_personne_1",
        "parts_personne_1",
        "civilite_personne_2",
        "prenom_personne_2",
        "nom_personne_2",
        "parts_personne_2",
        "civilite_personne_3",
        "prenom_personne_3",
        "nom_personne_3",
        "parts_personne_3",
        "denomination_societe_nouvel_associe",
        "plage_parts_total",
        "plage_parts_personne_1",
        "plage_parts_personne_2",
        "plage_parts_societe_nouvel_associe",
        "civilite_personne_4",
        "prenom_personne_4",
        "nom_personne_4",
        "parts_personne_4",
        "plage_parts_personne_4",
    ),
    "DOC-032": (
        "lieu_signature",
        "date_signature",
        "montant_droits_enregistrement",
        "prenom_signataire",
        "nom_signataire",
    ),
    "DOC-033": (
        "civilite_cedant",
        "prenom_cedant",
        "nom_cedant",
        "profession_cedant",
        "date_naissance_cedant",
        "ville_naissance_cedant",
        "departement_naissance_cedant",
        "nationalite_cedant",
        "adresse_cedant",
        "situation_maritale_cedant",
        "civilite_conjoint_cedant",
        "prenom_conjoint_cedant",
        "nom_conjoint_cedant",
        "ordre_departemental_cedant",
        "numero_ordre_cedant",
        "numero_rpps_cedant",
        "denomination_societe_cessionnaire",
        "capital_social_cessionnaire",
        "adresse_siege_cessionnaire",
        "ville_rcs_cessionnaire",
        "denomination_societe_cedee",
        "nb_parts_cedees",
        "capital_social_societe_cedee",
        "nb_parts_total_societe_cedee",
        "ville_rcs_societe_cedee",
        "numero_rcs_societe_cedee",
        "civilite_associe_societe_cedee_1",
        "prenom_associe_societe_cedee_1",
        "nom_associe_societe_cedee_1",
        "civilite_associe_societe_cedee_3",
        "prenom_associe_societe_cedee_3",
        "nom_associe_societe_cedee_3",
        "plage_parts_cedees",
        "prix_unitaire_part_lettres",
        "prix_unitaire_part",
        "prix_global_parts_lettres",
        "prix_global_parts",
        "montant_credit_vendeur",
        "duree_credit_vendeur",
        "taux_credit_vendeur",
        "lieu_signature",
        "nombre_exemplaires_lettres",
        "civilite_representant_cessionnaire_courte",
        "prenom_representant_cessionnaire",
        "nom_representant_cessionnaire",
    ),
    "DOC-005": (
        "lieu_signature",
        "date_signature",
        "civilite",
        "prenom",
        "nom",
        "date_du_jour",
        "denomination_societe",
        "forme_sociale_complete",
        "apport_personne_1",
        "apport_lettres_personne_1",
        "prenom_conjoint",
        "nom_conjoint",
    ),
    "DOC-006": (),
    "DOC-013": (),
    "DOC-014": (),
    "DOC-007": (
        "date_du_jour",
        "civilite_bailleur",
        "prenom_bailleur",
        "nom_bailleur",
        "profession_bailleur",
        "date_naissance_bailleur",
        "ville_naissance_bailleur",
        "nationalite_bailleur",
        "adresse_bailleur",
        "civilite_locataire",
        "prenom_locataire",
        "nom_locataire",
        "profession_locataire",
        "date_naissance_locataire",
        "ville_naissance_locataire",
        "nationalite_locataire",
        "adresse_locataire",
        "date_bail",
        "denomination_societe",
        "ville_rcs",
        "adresse_siege",
        "civilite_courte_locataire",
        "lieu_signature",
        "nombre_exemplaires_lettres",
        "date_signature",
    ),
    "DOC-008": (
        "nom_banque",
        "lieu_signature",
        "date_signature",
        "civilite_destinataire",
        "prenom_destinataire",
        "nom_destinataire",
        "denomination_societe",
        "civilite_vendeur",
        "prenom_vendeur",
        "nom_vendeur",
        "denomination_societe_acquereur",
        "prenom_signataire",
        "nom_signataire",
    ),
    "DOC-009": (
        "civilite_vendeur",
        "prenom_vendeur",
        "nom_vendeur",
        "profession_vendeur",
        "date_naissance_vendeur",
        "ville_naissance_vendeur",
        "departement_naissance_vendeur",
        "nationalite_vendeur",
        "adresse_vendeur",
        "adresse_exercice_vendeur",
        "numero_siren_vendeur",
        "ordre_departemental_vendeur",
        "numero_ordre_vendeur",
        "situation_maritale_vendeur",
        "nom_conjoint_vendeur",
        "regime_matrimonial_vendeur",
        "denomination_societe_acquereur",
        "capital_social_acquereur",
        "adresse_siege_acquereur",
        "ville_rcs_acquereur",
        "numero_rcs_acquereur",
        "numero_siret_acquereur",
        "fonction_acquereur_representant",
        "civilite_acquereur_representant",
        "prenom_acquereur_representant",
        "nom_acquereur_representant",
        "adresse_cabinet",
        "telephone_cabinet",
        "annees_acquisition_patientele",
        "description_origine_propriete",
        "date_bail",
        "duree_bail",
        "date_debut_bail",
        "date_fin_bail",
        "superficie_local",
        "date_reconduction_bail_1",
        "date_reconduction_bail_2",
        "loyer_mensuel",
        "exercice_1",
        "chiffre_affaires_1",
        "resultat_1",
        "exercice_2",
        "chiffre_affaires_2",
        "resultat_2",
        "exercice_3",
        "chiffre_affaires_3",
        "resultat_3",
        "prix_cession_lettres",
        "prix_cession",
        "prix_elements_corporels_lettres",
        "prix_elements_corporels",
        "prix_elements_incorporels_lettres",
        "prix_elements_incorporels",
        "montant_credit_vendeur",
        "duree_credit_vendeur",
        "taux_credit_vendeur",
        "majoration_interet_retard",
        "nb_parts_scm_a_ceder",
        "date_immatriculation_acquereur",
        "date_inscription_ordre_acquereur",
        "lieu_signature",
        "nombre_exemplaires_lettres",
        "nombre_pages_lettres",
        "signature_acquereur",
        "signature_vendeur",
    ),
    "DOC-010": (
        "civilite_vendeur",
        "prenom_vendeur",
        "nom_vendeur",
        "profession_vendeur",
        "date_naissance_vendeur",
        "ville_naissance_vendeur",
        "pays_naissance_vendeur",
        "nationalite_vendeur",
        "adresse_vendeur",
        "adresse_cabinet",
        "numero_siren_vendeur",
        "ordre_departemental_vendeur",
        "numero_ordre_vendeur",
        "situation_maritale_vendeur",
        "civilite_conjoint_vendeur",
        "prenom_conjoint_vendeur",
        "nom_conjoint_vendeur",
        "regime_matrimonial_vendeur",
        "denomination_societe_acquereur",
        "forme_sociale_acquereur",
        "capital_social_acquereur",
        "adresse_siege_acquereur",
        "ville_rcs_acquereur",
        "fonction_acquereur_representant",
        "civilite_acquereur_representant",
        "prenom_acquereur_representant",
        "nom_acquereur_representant",
        "nature_fonds_liberal",
        "adresse_locaux",
        "telephone_cabinet",
        "date_origine_propriete",
        "date_bail",
        "duree_bail",
        "date_debut_bail",
        "date_fin_bail",
        "date_reconduction_bail_1",
        "date_reconduction_bail_2",
        "superficie_local",
        "loyer_mensuel",
        "exercice_1",
        "chiffre_affaires_1",
        "resultat_1",
        "exercice_2",
        "exercice_3",
        "chiffre_affaires_3",
        "resultat_3",
        "prix_cession_lettres",
        "prix_cession",
        "prix_elements_corporels_lettres",
        "prix_elements_corporels",
        "prix_elements_incorporels_lettres",
        "prix_elements_incorporels",
        "date_realisation_limite",
        "montant_pret",
        "taux_pret",
        "duree_pret",
        "lieu_signature",
        "nombre_exemplaires_lettres",
        "nombre_pages_lettres",
        "date_signature",
        "signature_acquereur",
        "signature_vendeur",
    ),
    "DOC-011": (
        "civilite_vendeur",
        "prenom_vendeur",
        "nom_vendeur",
        "profession_vendeur",
        "date_naissance_vendeur",
        "ville_naissance_vendeur",
        "departement_naissance_vendeur",
        "nationalite_vendeur",
        "adresse_vendeur",
        "situation_maritale_vendeur",
        "regime_matrimonial_vendeur",
        "civilite_conjoint_vendeur",
        "prenom_conjoint_vendeur",
        "nom_conjoint_vendeur",
        "ordre_departemental_vendeur",
        "numero_rpps_vendeur",
        "denomination_societe_acquereur",
        "forme_sociale_acquereur",
        "capital_social_acquereur",
        "adresse_siege_acquereur",
        "ville_rcs_acquereur",
        "numero_rcs_acquereur",
        "fonction_acquereur_representant",
        "telephone_cabinet",
        "civilite_precedent_proprietaire",
        "prenom_precedent_proprietaire",
        "nom_precedent_proprietaire",
        "date_origine_propriete",
        "prix_origine_propriete",
        "date_bail",
        "duree_bail",
        "exercice_1",
        "chiffre_affaires_1",
        "resultat_1",
        "exercice_2",
        "chiffre_affaires_2",
        "resultat_2",
        "exercice_3",
        "chiffre_affaires_3",
        "resultat_3",
        "prix_cession_lettres",
        "prix_cession",
        "prix_elements_corporels_lettres",
        "prix_elements_corporels",
        "prix_elements_incorporels_lettres",
        "prix_elements_incorporels",
        "civilite_salarie_1",
        "prenom_salarie_1",
        "nom_salarie_1",
        "civilite_salarie_2",
        "prenom_salarie_2",
        "nom_salarie_2",
        "date_entree_jouissance",
        "lieu_signature",
        "nombre_pages_lettres",
        "date_signature",
    ),
    "DOC-012": (
        "civilite_vendeur",
        "prenom_vendeur",
        "nom_vendeur",
        "profession_vendeur",
        "date_naissance_vendeur",
        "ville_naissance_vendeur",
        "cp_naissance_vendeur",
        "nationalite_vendeur",
        "adresse_vendeur",
        "adresse_cabinet",
        "numero_siren_vendeur",
        "ordre_departemental_vendeur",
        "numero_ordre_vendeur",
        "situation_maritale_vendeur",
        "denomination_societe_acquereur",
        "forme_sociale_acquereur",
        "capital_social_acquereur",
        "ville_rcs_acquereur",
        "fonction_acquereur_representant",
        "adresse_locaux",
        "telephone_cabinet",
        "date_origine_propriete",
        "date_bail",
        "duree_bail",
        "date_debut_bail",
        "date_fin_bail",
        "date_reconduction_bail_1",
        "date_reconduction_bail_2",
        "superficie_local",
        "loyer_mensuel",
        "chiffre_affaires_1",
        "resultat_1",
        "chiffre_affaires_3",
        "resultat_3",
        "prix_cession_lettres",
        "prix_cession",
        "prix_elements_corporels_lettres",
        "prix_elements_corporels",
        "prix_elements_incorporels_lettres",
        "prix_elements_incorporels",
        "date_realisation_limite",
        "montant_pret",
        "lieu_signature",
        "nombre_exemplaires_lettres",
        "nombre_pages_lettres",
        "date_signature",
        "signature_acquereur",
        "signature_vendeur",
    ),
}

REUSE_RULE_VARIABLES: Final[dict[str, tuple[str, ...]]] = {
    rule.key: rule.fields for rule in SELARL_REUSE_RULES
}


def selarl_blocks() -> tuple[FormBlock, ...]:
    return SELARL_BLOCKS


def selarl_fields() -> tuple[FormField, ...]:
    return SELARL_FIELDS


def selarl_fields_by_block() -> dict[str, tuple[FormField, ...]]:
    fields_by_block: dict[str, list[FormField]] = {block.key: [] for block in SELARL_BLOCKS}
    for field in SELARL_FIELDS:
        fields_by_block[field.block_key].append(field)
    return {key: tuple(fields) for key, fields in fields_by_block.items()}


def selarl_reuse_rules() -> tuple[ReuseRule, ...]:
    return SELARL_REUSE_RULES


def selarl_document_specs() -> tuple[SelarlDocumentSpec, ...]:
    return SELARL_DOCUMENTS


def selarl_required_conditions() -> tuple[str, ...]:
    return SELARL_REQUIRED_CONDITIONS


def selarl_expected_documents(
    conditions: Mapping[str, object] | None = None,
) -> tuple[ExpectedDocument, ...]:
    return tuple(
        get_expected_documents(
            {"case_type": CaseType.SELARL, "conditions": dict(conditions or {})}
        )
    )


def selarl_generable_document_codes(
    conditions: Mapping[str, object] | None = None,
) -> tuple[str, ...]:
    return tuple(
        document.document_code
        for document in selarl_expected_documents(conditions)
        if document.availability == DocumentAvailability.GENERATABLE
        and document.document_code is not None
    )


def all_selarl_v2_variables() -> tuple[str, ...]:
    return tuple(
        sorted(
            {
                variable
                for variables in SELARL_V2_VARIABLES_BY_DOCUMENT.values()
                for variable in variables
            }
        )
    )


def selarl_variable_coverage() -> tuple[VariableCoverage, ...]:
    field_index = _field_variable_index()
    reuse_index = _reuse_variable_index()
    coverage: list[VariableCoverage] = []
    for variable in all_selarl_v2_variables():
        if variable in field_index:
            coverage.append(
                VariableCoverage(
                    variable,
                    VariableCoverageStatus.UI_FIELD,
                    field_key=field_index[variable],
                )
            )
        elif variable in reuse_index:
            coverage.append(
                VariableCoverage(
                    variable,
                    VariableCoverageStatus.REUSE_RULE,
                    reuse_rule_key=reuse_index[variable],
                )
            )
        else:
            coverage.append(
                VariableCoverage(
                    variable,
                    VariableCoverageStatus.TO_ARBITRATE,
                    note=(
                        "Variable V2 conservee dans la couverture ; champ UI "
                        "detaille a arbitrer avant generation document par document."
                    ),
                )
            )
    return tuple(coverage)


def validate_selarl_schema() -> tuple[str, ...]:
    issues: list[str] = []
    block_keys = {block.key for block in SELARL_BLOCKS}
    required_blocks = {
        "qualification",
        "societe",
        "siege_social",
        "professionnel_gerant",
        "ordre_professionnel",
        "associes",
        "mandataire_signataire",
        "regime_conjoint",
        "cession_cabinet",
        "bail",
        "scm",
        "banque_financement",
        "signature",
    }
    missing_blocks = sorted(required_blocks - block_keys)
    if missing_blocks:
        issues.append(f"Blocs SELARL manquants: {', '.join(missing_blocks)}")

    for field in SELARL_FIELDS:
        if field.block_key not in block_keys:
            issues.append(f"Champ {field.key} rattache a un bloc inconnu.")
        label = field.label.casefold().strip()
        if label == "adresse":
            issues.append(f"Champ {field.key} a un label adresse non qualifie.")
        if label in {"numero", "numéro", "voie", "ville", "code postal"}:
            issues.append(f"Champ {field.key} a un label d'adresse ambigu.")

    for document in SELARL_DOCUMENTS:
        if document.block_key not in block_keys:
            issues.append(f"Document {document.document_key} rattache a un bloc inconnu.")
    for code in ("DOC-013", "DOC-014"):
        document = next(
            item for item in SELARL_DOCUMENTS if item.document_code == code
        )
        if document.expected_availability == DocumentAvailability.GENERATABLE:
            issues.append(f"{code} ne doit pas etre generable dans le pilote SELARL.")

    coverage_variables = {item.variable for item in selarl_variable_coverage()}
    missing_coverage = sorted(set(all_selarl_v2_variables()) - coverage_variables)
    if missing_coverage:
        issues.append(f"Variables V2 sans couverture: {', '.join(missing_coverage)}")
    return tuple(issues)


def _field_variable_index() -> dict[str, str]:
    v2_variables = set(all_selarl_v2_variables())
    index: dict[str, str] = {}
    for field in SELARL_FIELDS:
        for variable in field.variables:
            if variable in v2_variables:
                index.setdefault(variable, field.key)
    return index


def _reuse_variable_index() -> dict[str, str]:
    v2_variables = set(all_selarl_v2_variables())
    index: dict[str, str] = {}
    for rule_key, variables in REUSE_RULE_VARIABLES.items():
        for variable in variables:
            if variable in v2_variables:
                index.setdefault(variable, rule_key)
    return index
